* blud
** distinguish special atoms from ordinary atoms.

User wants to have a target named ".AFTER" even though that's the name
of a special atom. Well, the user has to quote every instance of that.
So the atom name will be ".AFTER". The bound name will remove the quotes.

** Attributes
*** .AFTER
*** .BEFORE
*** .DEFAULT
*** .IGNORE
*** .PHONY
*** .PRECIOUS
*** .SILENT


** Phase 1
We are just copying input to output except there is a small transformation
for non-Lua lines. This is simplified because we don't let the user put
Lua code in column 1 unless it is the beginning of a compound statement:
    do/end
    (local) function/end
    if/else/elseif/end
    for/do/end
    while/do/end
    repeat/until
    local
** Phase 2
Now we execute the Lua program created by Phase 1 to create blud.phase2_text
and parse blud.phase2_text to create make variables and the
make dependency graph. In this parse, macros must be expanded.

** Parsing

A line is non-Lua if it starts in column 1 unless it
starts with one of:
    if    else   elseif then end do for repeat until while function local

A line is non-Lua if it starts in column 1 and:
    a) contains a '$' that is not '${'or
    b) starts with <identifier> <assign-op> or
    c) looks like a rule: one or more space-separated atoms followed by colon

A line is also non-lua if it is non-blank and indented following a rule

A line is also non-Lua if it is indented but starts with a $<whitespace>:
if ${OS} == "Windows" then
    $ OBJS += winrtl.obj
end

However, because of comments and string constants, these rules are not
sufficient.


A line is also non-lua if it is non-blank, indented, and follows
a rule.

** Secondary Expansion

Seems mostly about being able to modify rules with information not
available until all the rules have been parsed. Things probably better
done in Lua.

.POSTPARSE: a b
    function (target)
        print("Got called for each target. This one is: " .. target.NAME)
    end

Problems:
    a) just want a function call independent of any targets
    b) want function called with a list of targets

Waitaminute, "second expansion" is really kind of a subset of the :: operator.
Take all-too-tricksy example from page 18 of GNU make manual:

.SECONDEXPANSION
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib : $$($$(@_OBJS))
<><><><><>
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib :AddObjs: _OBJS

function AddObjs(target, prerequisites, action)
    $ $@ : $($@_OBJS)
end
<><><><><>



* log
** <2024-06-02 Sun>
Thinking of the dreaded implicit rule tangle. Was gonna say the "::" operator
is just hard-coded function that tries to generate the right rules from list
of source file prerequisites. But I think I've seen at least one make that
consistently had the user refer to source, not object, prerequisites.

program : a.c b.c

This has to eventually get translated to:

program : a.o b.o
    <linker command>

In a way, the "::" operator does what tools like CMAKE does, translating
a higher-level directive into detailed make rules.

This is relevant to the implicit rule problem, because the user writes:

program.exe : a.obj b.obj

which leaves the make utility to guess what the source files were for
a.obj and b.obj, even though the user knows perfectly well they were
.c files and would prefer to work with those names.

OTOH, there is the much less frequent case like this:

tool_name : a.c b.c   -- tool_name is a directory!
    cp $^ tool_name

Returning to this:

program : a.c b.c

It really should get translated to this:

program : a.o(a.c) b.o(b.c)
    <linker command>

where the parens indicate exactly what file the .o name was derived from.
GNU Make implicit rules for linking only really work if you happen to be
writing in C, since the object file dependencies lose the information
about what the source file extension was.

So, maybe the syntax should allow specifying which prerequisites are
source prerequisites, and what object files should be made from them.
So what would this mean:

program : <a.c <b.c

It means "a.c is a source file, look up what it should create". Hopefully,
the lookup finds a rule that says:

%.o : %.c
    $(CC) $(CFLAGS) -o $@ $<

<><><><><><><>
Meh, start over. User wants to write this:

program : a.c b.c

period. User types "blud program". blud updates "program", which first updates
"a.c". We don't know how to make a.c. In normal make, we see "a.c" exists and
has no recipe, so we just return its timestamp. But let's be different. Because
there is no recipe for "a.c", it's a "source". So let's look up our source
patterns and find that "a.c" matches "%.c", which is part of a rule that
says .c files produce .o files. So we "reflavor" a.c so it has two
components: source ("a.c") and output components ("a.o").

How/when do we know we have to build "a.o"? We kind of want to know that
"program" is of a TYPE that requires object files. But if "program"
does not exist, all we have to go on is its name, which (except under Windows)
will not typically contain a ".exe". 


** <2024-06-01 Sat>
I see the light! Can and should do away with macros. Let's say that this:

VAR = a $(B) c

translates to:

blud.set_var("VAR", function()
return "a " .. blud.get_var("B") .. " c"
end)

<><><><><>
OK, so we keep Phase 1, which does no macro expansion, just produces all the
non-lua lines of code. This allows Lua to control conditional appearance of
make rules and variable statements.

The resulting lines must be in one of the following two forms:
name <op> text

<text>* <colon_op> <text>*
(<indent><text>)*

Only <text> can contain variable expansions.




** <2024-05-31 Fri>
Phase 2. Can I expand macros on a per-line basis? Is macro expansion
different inside an action--do they all take place when the action
is executed? I think they must, else target-local variables would
not work.

So can Phase 2 just be macro expansion? Not quite, since it has to
know when it's in an action and not expand those macros.

Now is the time to fix macro problems!
What are macros for?
1) create values that can be referenced (list of filenames, command-line options, etc.)
2) create values that can be overridden on a target-scope basis
3) create values that can be overridden by command-line options
4) create multi-line values for actions that can be reused
5) create values with syntax friendly to space-separated lists
6) create delayed binding value references, so values can be built out of order
   IOW, this is value references


Now, you could always escape to Lua to make any variable you want:
do
    blud.macro_define("FOO", "Text of macro")
end

Ugh. See no wonderful improvements on macros and their "two flavors" ala GNU make.

Phase 2 must expand AND execute make code as it goes? Don't understand
expansion in actions.


a : b
$(ACTION)


** <2024-05-29 Wed>

1) parse blud file, create .luab
   non-Lua lines call function to append to text variable
2) run .luab, which creates variable with text of macros/rules
3) then expands text macros into another text variable
4) then parses text to create the graph
5) then uses the graph to update one or more targets

** <2024-05-28 Tue>

PROG = $(PROGNAME) : file1 $(OTHER)
PROGNAME = foo

if ${OS} == "Windows" then
    $ $(PROG)
end
fee : LATE = $(PROGNAME).exe
<><><><><><><><>
blud.append("PROG = $(PROGNAME) : file $(OTHER)\n")
blud.append("PROGNAME = foo\n")
blud.append("\n")
if blud.value("OS") == "Windows" then
    blud.append("$(PROG)")
end
blud.append("fee : LATE = $(PROGNAME).exe")
<><><><><><>
OK, have to write macro parser.



** <2024-05-27 Mon>
I started by parsing the blud file and converting it to Lua. But this cannot be
done in general at "compile" time, because of macros. Macros can introduce a runtime
requirement to do any sort of parsing I was trying to do at compile time. Worse, they
require character-by-character parsing because of:

objs = foo.$(OBJ)  -- can't tokenize until after macro expansion!

Actually, can avoid char-by-char processing if I first do a pass that expands
all the macros. Try some examples:

$(STUFF)
<><><><><><>
do
    local str = expand([=[
$(STUFF)
]=]
    parse(str)
end
<><><><><>
But that doesn't work either. Consider:
STUFF = a : b
$(STUFF)
    echo "Doing action"
Parser can't operate on each line independently, so when it hits echo line,
it needs to know previous line was a rule.
Also consider:
a : b
if ${OS} == "Windows" then
    $     echo "Doing Windows-only action"
end

It should help simplify if $ always identifies non-Lua code.
${} can still be used inside Lua code for convenient access to macros.

<><><><><><><>
We convert the blud text into Lua. We execute the Lua, which produces
the text of blud directives. We then parse the directives to create
macros and a dependency graph.  Finally, we use the graph to update
one or more targets.

STUFF = a : b
$(STUFF)
    echo "Doing action"
<><><><><><><>
do -- STUFF = a : b
    blud.macro_assign("STUFF", "a : b")
end
do -- $(STUFF)
    blud.append_text(blud.macro_expand("STUFF"))
    blud.append_text("\n")
end
do -- echo "Doing action"
    blud.append_text("    echo \"Doing action\"\n")
end

** <2024-05-25 Sat>

can blud rules be indented? e.g.:

if $(OS) == "Windows" then
    program : 
end


** <2024-05-14 Tue>



** <2024-05-13 Mon>

More than one lhs atom is just a syntax trick, so:
.ATOM : a b c d
means we're injecting code into these atoms. While:
a : b c d .ATOM
means .ATOM will get passed the rule before it is added to the graph



OK, really can't nail down graph when generating .lua code, because
variables can change at runtime via command-line options. So, what
is translation of:

a $(b) : c $(d)

do
    targets, prerequisites = blud.parse_rule([=[a $(b) : c $(d)]=])
end
-----------------------------------------------------

No, but wait. At least consider nailing down graph at compile time.
Because, you could always fall back to Lua code at run time that
does anything.

OK, can't completely nail down graph at compile time because of
wildcards, like "*.c". Don't want to give up that feature.

-----------------------------------------------------



.AFTER : a b c d e

a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when those atoms actions are to fire
c) it pretends the actions were successful
d) it asks to be called back when the parent finishes its action
e) when it is called back, it fires its own action finally

.BEFORE : a b c d e
a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when 




** <2024-05-12 Sun>

How about: primary way to inject Lua code into the process is via
special atoms. A special atom can appear on the left or right side of
a rule (though it may only make sense on one side or the other). The
name of the atom essentially identifies a Lua object that overrides 1
or more default behaviors of special atoms.  Function members of the
object will get called at various points in the processing. The object
will have access to a variety of information, including everything
about the rule.


** <2024-04-27 Sat>

When can custom Lua code be run? 

program: program.c
    cc -o program program.c

Now want to put products in a different directory.

all: program
