* blud
** distinguish special atoms from ordinary atoms.

User wants to have a target named ".AFTER" even though that's the name
of a special atom. Well, the user has to quote every instance of that.
So the atom name will be ".AFTER". The bound name will remove the quotes.

** Attributes
*** .AFTER
*** .BEFORE
*** .DEFAULT
*** .IGNORE
*** .PHONY
*** .PRECIOUS
*** .SILENT


** quoted pathnames
We need quotes, since for example:

if : a.c b.c

would be mis-interpreted as a Lua IF statement. However,
we can't have the backslash be the escape character in quotes
because of Windows path conventions.


** Appending to macro
GNU Make says you can't do this:

CFLAGS = $(CFLAGS) -O

But I think I can handle that. CFLAGS is always a reference to an
anonymous function that returns a string. So this problem solves itself!
Almost. The initial definition of CFLAGS is a reference to an anonymous
function that expands its text. Any variable references in that
definition are indirect-by-name function calls to expand *that* variable.
When (re)defining CFLAGS, we are constructing another anonymous function,
the only difference is that when we encounter embedded self-reference,
we use a direct pointer to the anonymous function instead of indirect-by-name.
The anonymous function associated with CFLAGS will get clobbered by
a new one, and the previous anonymous function only exists via an embedded
reference.

Really not sure why GNU Make didn't do it this way. It essentially does
almost all the same work by allowing a += operator. I think there's no
need for the GNU Make "two flavors" of variables.

I guess the issue is "functions":

    Another disadvantage is that any functions referenced in the
    definition will be executed every time the variable is expanded. This
    makes make run slower; worse, it causes the wildcard and shell
    functions to give unpredictable results because you cannot easily
    control when they are called, or even how many times

CFILES = $(wildcard *.c)




** Phase 1
We are just copying input to output except there is a small transformation
for non-Lua lines. This is simplified because we don't let the user put
Lua code in column 1 unless it is the beginning of a compound statement:
    do/end
    (local) function/end
    if/else/elseif/end
    for/do/end
    while/do/end
    repeat/until
    local
** Phase 2
Now we execute the Lua program created by Phase 1 to create blud.phase2_text
and parse blud.phase2_text to create make variables and the
make dependency graph. In this parse, macros must be expanded.

** Parsing

A line is non-Lua if it starts in column 1 unless it
starts with one of:
    if    else   elseif then end do for repeat until while function local

A line is non-Lua if it starts in column 1 and:
    a) contains a '$' that is not '${'or
    b) starts with <identifier> <assign-op> or
    c) looks like a rule: one or more space-separated atoms followed by colon

A line is also non-lua if it is non-blank and indented following a rule

A line is also non-Lua if it is indented but starts with a $<whitespace>:
if ${OS} == "Windows" then
    $ OBJS += winrtl.obj
end

However, because of comments and string constants, these rules are not
sufficient.


A line is also non-lua if it is non-blank, indented, and follows
a rule.

*** Parsing: identifying blud statements
A blud statement must look like:
a) name <assign-op> text
b) <name-list> <colon-op> <name-list>
c) <name-list> <colon-op> <name-list>
   <indent><actions>

** GNU Make
*** macro fails
SET = A = you da man
$(SET)

a :
	echo $(A)
	echo $(SET)

This Makefile gives you the dreaded "missing separator" error on
line 2, even though the documentation says:

    Variable references can be used in any context: targets,
    prerequisites, recipes, most directives, and new variable values.

However, this quite similar construct works as expected:

SET = a : b
$(SET)

b : ; echo making b

a :
	echo $(SET)

And this works as well:
COLON = :
a $(COLON) b

b : ; echo making b

a :
	echo $(SET)

So what exactly are the rules for where variables can be used? Who knows?


** Secondary Expansion

Seems mostly about being able to modify rules with information not
available until all the rules have been parsed. Things probably better
done in Lua.

.POSTPARSE: a b
    function (target)
        print("Got called for each target. This one is: " .. target.NAME)
    end

Problems:
    a) just want a function call independent of any targets
    b) want function called with a list of targets

Waitaminute, "second expansion" is really kind of a subset of the :: operator.
Take all-too-tricksy example from page 18 of GNU make manual:

.SECONDEXPANSION
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib : $$($$(@_OBJS))
<><><><><>
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib :AddObjs: _OBJS

function AddObjs(target, prerequisites, action)
    $ $@ : $($@_OBJS)
end
<><><><><>



* log
** <2024-06-13 Thu>
Make macros do something. Why am I so slow?  Let a macro always
be a function that returns a string. If it was a ":=" style macro,
the string is constant. Otherwise, the string is generated from
an array of string constants and references to other macros
(functions). Don't worry about macros with arguments for now.

Simpler: always reparse late-binding macro. Then, a macro is
always a string, just have to keep track of whether it needs
expanding or not when you ask for its value.


** <2024-06-08 Sat>
Another day, another run at progress.  Phase 1 produced a Lua program.
Phase 2 produces blud.phase2_text, the actual bludfile directives
that will be read in this invocation of blud. Phase 3 takes each line,
performs any required variable substitution, then executes that line
(which either performs variable assignment, a dependency rule, or
associates action text). No multi-line variables allowed except in
actions, so can really do this line-by-line, no input stacking.
Every line in will be a line out.


** <2024-06-07 Fri>
to expand macros, must also a) execute macro definitions as they appear and
b) detect indented actions so we don't expand them. And c) detecting indented
actions requires detecting dependency lines. Can't cleanly separate macro
expansion from parsing!

State 0: expand all macros, char by char
    
    got 1st "name"

UGH! Implausible to ever generate good error messages! Back to restricting
use of macros.

Name <assignop> macros_OK
macros_OK <depend_op> macros_OK
    macros_OK

special:

build <name>
end
define <name>
end
define /<name>
end

Macro expansion pass:
1) if looks like macro assign op, do the operation, line won't appear in output
2) if looks like dependency line, expand all macros (multi-line not ok), copy to output
3) if indented, just copy to output

example:

define ACTION
cp $^ foo
echo foo!
end
OBJS = a.o b.o c.o
program : $(OBJS)
    $(ACTION)
<><><><><>
program : a.o b.o c.o
    $(ACTION)



** <2024-06-06 Thu>


** <2024-06-05 Wed>

OK, let's make phase 2? 3? expand macros. We assume that we can
rigorously identify non-lua lines even in the face of macros. Phase 1
was creating the Lua code that only has to be regenerated if the
bludfile changes.  Phase 2 executes that code to create
blud.phase2_text.

Should we expand macros while appending to blud.phase2_text, or in a
separate pass? Separate pass! Make things as clear as possible. Want
access to text output of phase 2 that shows what (including macros)
is the "real" input to the graph construction. Let's see problems:

FOO = FEE = a.c
$(FOO)

This is an example GNU Make fails on. We see $(FOO), we're not
in a macro definition, we're not in an action, so we expand it.
Ah, that's why GNU Make fails, I bet. Maybe. You have to not
only expand it, but then execute it (phase 4?).

So, the trick in a macro expansion pass is that there are two
contexts where macros should not be expanded: macro definitions
and actions. But those contexts cannot always be identified
in a single-pass macro expansion:

NAME   = Foo
VALUE  = Fee
MACDEF = $(NAME) = 
$(MACDEF) $(VALUE)
-- expands to
Foo = Fee

Well, maybe the only problem is knowing we're in an action:

X = foo!
RULE = a : b
define ACTION
    echo $(X)
end
$(RULE)
$(ACTION)
-- expands to
X = foo!
RULE = a : b
define ACTION
    echo $(X)
end
a : b
    echo $(X)


Really, really want to think in terms of variables instead of macros.
If you want to do weird stuff, do it in Lua!

What if: variables are only expanded in lhs/rhs of rule or in actions?
If you want them expanded anywhere else, you have to explicitly
say so.

Or maybe we just support simple macros and if you get into trouble
it's your own fault for not switching to Lua.

Do we recognize a macro definition in the expansion of a
macro? That is, the exact case where GNU make fails:

SET = A = you da man
$(SET)
a :
	echo $(A)
	echo $(SET)

OK, let's go back to variables, not macros. Variable/function
invocations can only happen inside variable definition,
inside variable invocation, or inside action. THEN can I have
a simple expansion pass?

And... also want to handle spaces inside filenames. Two main
uses for variables are actions (command flags) and filenames.
What if I DO have two flavors of variable, but they are:
array of filenames, and text.

OBJS      = { "file with space.txt" a.c b.c c.c }
EXTRA_OBJ = d.c
program   : $(OBJS) $(EXTRA_OBJ)


** <2024-06-04 Tue>

Why am I stuck? Little things. What are the exact rules for where
variable expansions can occur?  Desire to indent inside build/end.
Can I expand variables in phase 2? Big things. How to handle inference
rules. How to handle source prerequisites. How to detect executable.

Really want to expand variables in phase 2 because this potentially
helps make error messages better. Can easily print out "expanded"
lines for error messages, so user sees what the line became.

OK, so every non-lua line must look like rule or variable
assignment. Variables can only be expanded on rhs of variable
definition, or either side of dependency rule. Because: before
macro expansion... Hmmm, not sure.



Do I really have to introduce build/end? Certainly want to
avoid requiring conditional code to make different builds build
differently. build/end is basically away to group blud statements,
and must face the problem of wanting to indent statements that
are otherwise supposed to start in column 1. But we already
have indentation.  What about:

debug :BUILD:
    OWD = ./debug
    CFLAGS = -g
    program : debug.c
        $(LINK) <stuff>

Better:

debug : .BUILD

Still, a "build" directive is clearer, isn't it? And maybe it
should just allow indentation:

build debug=./debug
    CFLAGS = -g
    program : debug.c
        $(LINK) <stuff>
end

But "just allow indentation" collides with our simple rule for
identifying Lua: a Lua keyword starting in column 1.

OK, blud statements only require indentation to identify actions,
which must follow a non-indented rule. So, inside a "build" directive,
the indentation level is set by the very first line, which cannot be
(conceptually) indented:

build debug
    CFLAGS = -g
    if $(OS) == "Windows" then -- started in "virtual" column 1!
        program : windows.c
    end
end


** <2024-06-03 Mon>
CMake is a giant-ass preprocessor for make, essentially. But we should
be able to get more or less equivalent functionality just by extending
the general mechanisms of make, which is what blud can do.

Back to this:

program : a.c b.c

Really need to generate additional rules for this while building
the update graph. Initially, the graph is as written: program is
target and "a.c b.c" are the prerequisites. We *could* also consult
the filesystem at this point for more information. "program" may
or may not exist, but for sure we have no recipe for updating it.
Really, "program" is a dead end for determining how it should be
updated. So we step through its prerequisites.

"a.c" can tell us that it can produce "a.o", and "a.o" can tell us
that it is most likely used to make ".exe", and second most likely
used to make ".lib". So we guess that program is a ".exe", which
the user could make explicit with:

program :.TYPE: exe   -- I bet there's a better syntax!








** <2024-06-02 Sun>
Thinking of the dreaded implicit rule tangle. Was gonna say the "::" operator
is just hard-coded function that tries to generate the right rules from list
of source file prerequisites. But I think I've seen at least one make that
consistently had the user refer to source, not object, prerequisites.

program : a.c b.c

This has to eventually get translated to:

program : a.o b.o
    <linker command>

In a way, the "::" operator does what tools like CMAKE does, translating
a higher-level directive into detailed make rules.

This is relevant to the implicit rule problem, because the user writes:

program.exe : a.obj b.obj

which leaves the make utility to guess what the source files were for
a.obj and b.obj, even though the user knows perfectly well they were
.c files and would prefer to work with those names.

OTOH, there is the much less frequent case like this:

tool_name : a.c b.c   -- tool_name is a directory!
    cp $^ tool_name

Returning to this:

program : a.c b.c

It really should get translated to this:

program : a.o(a.c) b.o(b.c)
    <linker command>

where the parens indicate exactly what file the .o name was derived from.
GNU Make implicit rules for linking only really work if you happen to be
writing in C, since the object file dependencies lose the information
about what the source file extension was.

So, maybe the syntax should allow specifying which prerequisites are
source prerequisites, and what object files should be made from them.
So what would this mean:

program : <a.c <b.c

It means "a.c is a source file, look up what it should create". Hopefully,
the lookup finds a rule that says:

%.o : %.c
    $(CC) $(CFLAGS) -o $@ $<

<><><><><><><>
Meh, start over. User wants to write this:

program : a.c b.c

period. User types "blud program". blud updates "program", which first updates
"a.c". We don't know how to make a.c. In normal make, we see "a.c" exists and
has no recipe, so we just return its timestamp. But let's be different. Because
there is no recipe for "a.c", it's a "source". So let's look up our source
patterns and find that "a.c" matches "%.c", which is part of a rule that
says .c files produce .o files. So we "reflavor" a.c so it has two
components: source ("a.c") and output components ("a.o").

How/when do we know we have to build "a.o"? We kind of want to know that
"program" is of a TYPE that requires object files. But if "program"
does not exist, all we have to go on is its name, which (except under Windows)
will not typically contain a ".exe" or any other clue. Nor can we examine
the file, since it will often not exist.


<><><><><><>
Does "build" need to be a 1st-class concept in blud? Suppose we have
builds debug and release and we want to build debug/foo.o. Our bludfile
looks like:

{debug} : CFLAGS = -g
{debug} : program
program : foo.c

We cannot just say "blud foo.o" or even "blud debug/foo.o" because
neither of those targets implicitly reference the {debug} build.
First of all, for this to work, we really need to construct the entire
build graph, not just build it as needed. Let's translate the above
example into GNU make directives:

debug : CFLAGS = -g
debug : debug/program
debug/program : debug/foo.o
    <default link command>
debug/foo.o : foo.c
    <default CC command with OWD=debug>

Now, "debug/foo.o" is a known target. We could even, given "blud foo.o"
decide that ./foo.o is not a known target and look for $(OWD)/foo.o,
which would match "debug/foo.o". But we generally need to know what OWD
is set to to do anything, which is very close to just saying we need
to know which build the user is working with to do anything.

OK, so default build if no build directives is OWD=., works like
normal make. Else, if one or more build definitions and no specification
from environment or command-line, default build is the first one defined.

So, defining a build is essentially just assigning a name to the OWD.
The name is separate from the OWD to allow it to be short if the OWD
is long. In the most common case (debug/release) they would likely
be identical and the user need not distinguish the build name from
the OWD.

What syntax for defining a build? In the maximal case we need:
- build name
- OWD value
- zero or more build-level variable assignments
- zero or more build-specific rules
This suggests we need an enclosing construct with a begin/end line,
which is slightly ugly if we're requiring rules and variable assignments
to start in column 1. But let's go with that for the moment:

build debug=./debug
CFLAGS = -g
if $(OS) == "Windows" then
    $ program : debugger.c
end
end

This is slightly more verbose than I hoped, since a common construct
will start with:

build debug  -- creates ./debug if necessary, sets OWD and BUILD_OWD
CFLAGS = -g
end
build release
end
-- top-level variable BUILD is set to name of build

Note that you could do this:
function DebugBuild()
    if $(OS) == "Windows then
        $ program : debugger.c
    end
end
build debug=./debug
    $ CFLAGS = -g
    $ ${DebugBuild()}
end


** <2024-06-01 Sat>
I see the light! Can and should do away with macros. Let's say that this:

VAR = a $(B) c

translates to:

blud.set_var("VAR", function()
return "a " .. blud.get_var("B") .. " c"
end)

<><><><><>
OK, so we keep Phase 1, which does no macro expansion, just produces all the
non-lua lines of code. This allows Lua to control conditional appearance of
make rules and variable statements.

The resulting lines must be in one of the following two forms:
name <op> text

<text>* <colon_op> <text>*
(<indent><text>)*

Only <text> can contain variable expansions.




** <2024-05-31 Fri>
Phase 2. Can I expand macros on a per-line basis? Is macro expansion
different inside an action--do they all take place when the action
is executed? I think they must, else target-local variables would
not work.

So can Phase 2 just be macro expansion? Not quite, since it has to
know when it's in an action and not expand those macros.

Now is the time to fix macro problems!
What are macros for?
1) create values that can be referenced (list of filenames, command-line options, etc.)
2) create values that can be overridden on a target-scope basis
3) create values that can be overridden by command-line options
4) create multi-line values for actions that can be reused
5) create values with syntax friendly to space-separated lists
6) create delayed binding value references, so values can be built out of order
   IOW, this is value references


Now, you could always escape to Lua to make any variable you want:
do
    blud.macro_define("FOO", "Text of macro")
end

Ugh. See no wonderful improvements on macros and their "two flavors" ala GNU make.

Phase 2 must expand AND execute make code as it goes? Don't understand
expansion in actions.


a : b
$(ACTION)


** <2024-05-29 Wed>

1) parse blud file, create .luab
   non-Lua lines call function to append to text variable
2) run .luab, which creates variable with text of macros/rules
3) then expands text macros into another text variable
4) then parses text to create the graph
5) then uses the graph to update one or more targets

** <2024-05-28 Tue>

PROG = $(PROGNAME) : file1 $(OTHER)
PROGNAME = foo

if ${OS} == "Windows" then
    $ $(PROG)
end
fee : LATE = $(PROGNAME).exe
<><><><><><><><>
blud.append("PROG = $(PROGNAME) : file $(OTHER)\n")
blud.append("PROGNAME = foo\n")
blud.append("\n")
if blud.value("OS") == "Windows" then
    blud.append("$(PROG)")
end
blud.append("fee : LATE = $(PROGNAME).exe")
<><><><><><>
OK, have to write macro parser.



** <2024-05-27 Mon>
I started by parsing the blud file and converting it to Lua. But this cannot be
done in general at "compile" time, because of macros. Macros can introduce a runtime
requirement to do any sort of parsing I was trying to do at compile time. Worse, they
require character-by-character parsing because of:

objs = foo.$(OBJ)  -- can't tokenize until after macro expansion!

Actually, can avoid char-by-char processing if I first do a pass that expands
all the macros. Try some examples:

$(STUFF)
<><><><><><>
do
    local str = expand([=[
$(STUFF)
]=]
    parse(str)
end
<><><><><>
But that doesn't work either. Consider:
STUFF = a : b
$(STUFF)
    echo "Doing action"
Parser can't operate on each line independently, so when it hits echo line,
it needs to know previous line was a rule.
Also consider:
a : b
if ${OS} == "Windows" then
    $     echo "Doing Windows-only action"
end

It should help simplify if $ always identifies non-Lua code.
${} can still be used inside Lua code for convenient access to macros.

<><><><><><><>
We convert the blud text into Lua. We execute the Lua, which produces
the text of blud directives. We then parse the directives to create
macros and a dependency graph.  Finally, we use the graph to update
one or more targets.

STUFF = a : b
$(STUFF)
    echo "Doing action"
<><><><><><><>
do -- STUFF = a : b
    blud.macro_assign("STUFF", "a : b")
end
do -- $(STUFF)
    blud.append_text(blud.macro_expand("STUFF"))
    blud.append_text("\n")
end
do -- echo "Doing action"
    blud.append_text("    echo \"Doing action\"\n")
end

** <2024-05-25 Sat>

can blud rules be indented? e.g.:

if $(OS) == "Windows" then
    program : 
end


** <2024-05-14 Tue>



** <2024-05-13 Mon>

More than one lhs atom is just a syntax trick, so:
.ATOM : a b c d
means we're injecting code into these atoms. While:
a : b c d .ATOM
means .ATOM will get passed the rule before it is added to the graph



OK, really can't nail down graph when generating .lua code, because
variables can change at runtime via command-line options. So, what
is translation of:

a $(b) : c $(d)

do
    targets, prerequisites = blud.parse_rule([=[a $(b) : c $(d)]=])
end
-----------------------------------------------------

No, but wait. At least consider nailing down graph at compile time.
Because, you could always fall back to Lua code at run time that
does anything.

OK, can't completely nail down graph at compile time because of
wildcards, like "*.c". Don't want to give up that feature.

-----------------------------------------------------



.AFTER : a b c d e

a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when those atoms actions are to fire
c) it pretends the actions were successful
d) it asks to be called back when the parent finishes its action
e) when it is called back, it fires its own action finally

.BEFORE : a b c d e
a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when 




** <2024-05-12 Sun>

How about: primary way to inject Lua code into the process is via
special atoms. A special atom can appear on the left or right side of
a rule (though it may only make sense on one side or the other). The
name of the atom essentially identifies a Lua object that overrides 1
or more default behaviors of special atoms.  Function members of the
object will get called at various points in the processing. The object
will have access to a variety of information, including everything
about the rule.


** <2024-04-27 Sat>

When can custom Lua code be run? 

program: program.c
    cc -o program program.c

Now want to put products in a different directory.

all: program
