* blud
** ChatGPT conversation head

I'm building a replacement for GNU Make using luajit hosted in C.
It's called "blud".
Assume all Lua questions refer to luajit unless otherwise specified,
and likewise assume I'm using C not C++.

Operators:
The "target1 ... targetN : dependent1 ... dependentN" syntax is
generalized by treating ":" as a particular case of an "operator".
Operators are of the form ":NAME:", where NAME is the moniker
specifying what the operator does. Each rule using an operator
may have targets, dependents, and an action, but the meaning
of those things may vary widely. One thing that does not
vary is this:

target1 ... targetN : whatever

ALWAYS means the same as:

target1 : whatever
...
targetN : whatever

Source operator:
Although operators apart from the single-colon dependency operator
have names, there is an operator that has a null name: "::". This
is called the "source operator". It is used in the common case
of specifying a rule to build an executable or library. It examines
all its arguments and generates the necessary "normal" rules to
correctly build its target. In particular, you are allowed
and encouraged to give the source operator source instead of
object file names and it will "do the right thing". For
example this:

prog :: a.c b.c foo.a

would generate rules like this:

prog : a.o b.o foo.a
    $(CC) -o $@ $^
a.o : a.c
b.o : b.c

Integrating Lua:
Instead of trying to extend a macro language to include programming
constructs (as GNU Make does), blud integrates Lua into its syntax.
Like most make derivatives, blud is fairly line-oriented. It examines
each line to see what "type" of thing it is before evaluating it.
If a line begins with a Lua keyword that implies block structure
(do/if/else/function/for/etc.) blud begins treating the text as
Lua code instead of blud directives. It only examines lines that
start with a non-blank character from that point to figure out
where the Lua code segment ends. Here's an example bludfile:

do
    print("I'll be printed first before graph is even constructed!")
end

all :
    echo "I'll be printed separate, while traversing graph!"

For the most part, blud just blindly copies Lua code to a buffer where it
will later compile and execute it. However, Lua code can access bludfile
macros via the "$" syntax. Example:

do
    if $(OS) == "Windows" then
        error("this bludfile doesn't work on windows!")
    end
end

The "$(OS)" expression will be translated to a call to an internal
function that locates the named macro and returns its value as
a Lua string.

Lua code can also have embedded bludfile directives. These are any
lines that are indented, then start with a "$" followed by at least
one space. If the text following the "$" is followed by more
than one space, it must be an action for an immediately preceding
rule. Example:

do
    if $(OS) == "Windows" then
        -- add Windows CRT to link for prog
        $ prog : wincrt.obj
    end
end

prog :: prog.c util.c

Multi-language Actions:
Actions in GNU Make are written in shell script. However blud actions
can contain a mix of Lua, shell, and blud directives! This is
parsed much like the outermost bludfile, except that the start
indentation of the action is used to decide when parts of the
action are "indented". Also, the default language in the bludfile
is blud directives, but the default language in an action is
shell commands. Here's an example:

add_deps :
    echo "adding 2 dependencies to 'main'"
    $ main : x.o y.o
    do
        print("the time is> " ..os.date("%Y-%m-%d %H:%M:%S"))
    end

Atoms:
As part of generalizing the original Feldman make syntax, blud
follows the lead of Alcatel's nmake and calls the names that
appear in rules "atoms". Atoms may correspond to files, but may
not. When asked to update an atom, blud goes through a step
called "binding". This is when the atom becomes associated
with a particular file.

Summary:
This is an overview of some key ways that blud's proposed design
differs from GNU Make, to help orient you when asked to consider
design ideas and other aspects of building this utility.


** Use case examples
*** https://stackoverflow.com/questions/78911443/makefile-for-2-targets-with-different-prerequisites-but-with-single-command-to-g

So, "grouped targets" let you say that an action updates more than
one target:

target_a target_b &: src_a src_b
    build_a_and_b

The problem is: this rule lets make know that the action updates both
targets, but it also forces both targets to depend on all the sources.

Basically, the need is for an action to specify that it updated
additional targets.

Solution: operator that marks targets updated.

target_a : src_a
    build_a_and_b
    $ target_a target_b :UPDATED:
target_b : src_b
    build_a_and_b
    $ target_a target_b :UPDATED:

My first example of an operator that is ONLY useful inside an
action, something there is no concept for in GNU Make.

Note that this depends on the algorithm we use to see whether
a target is updated. If we re-check the filesystem timestamp
just before deciding we need to update a target, then all this
is not necessary--except then the -n option may produce
different results than actually running the makefile would
produce!

*** https://stackoverflow.com/questions/78899903/how-to-create-a-make-target-which-is-an-implicit-dependency-for-all-other-target

How to create a make-target which is an implicit dependency for all other targets?

this can actually easy with blud and impossible with Gnu make:

We already have:

.BEFORE: pre
pre:
    echo "I'll run just before the parent target!"

fee: ; echo "I foolishly think I'll come out on time"

foo: pre fee
    echo "that pre message will come out just before me"

We assign an attribute to a target that polymorphs the
default execution algorithm. But in this case, we want to
polymorph the super atom. This is not as similar
as I hoped.

Maybe something like this:
.DO_ACTION: -- applies to super-atom if no explicit targets
    echo "I run instead of default DO_ACTION!"
    .DO_ACTION

ugh. Definitely not fleshed out.


*** https://stackoverflow.com/questions/78881089/how-to-find-the-prerequisite-from-list-based-on-target-list

Root problem here is GNU Make has no easy way to iterate
across a word list as though it were an array. Problem really
requires pairing words in order from two lists. This would be
easy in blud using Lua if we support turning blud variables
into Lua arrays:

ADDFILES = Makefile  blud.lua          Figure1.pic
ASFILES  = Makefile  test.log          foo.pic
DESTDIR  = /tmp/
DESTFILES = $(addprefix $(DESTDIR),$(ASFILES))

all : $(DESTFILES)

do
    local dest_files = $[DESTFILES]
    local src_files  = $[ADDFILES]
    local count = #dest_files
    for i = 1, count do
        $ -- emit rule and action here
    end
end

*** https://stackoverflow.com/questions/78866240/makefile-implicit-rule-with-sub-dirs

Now this is interesting because the OP wants to keep a directory tree
of sources, but keep one Makefile and all output files in the top directory.
He wants to list source files like ./src/sub_whatever/foo.c and have the
makefile automatically create (if needed) a parallel ./sub_whatever/ directory
and put the output files there.

Interesting annoyance here:
tool: main.o sub/file.o
	gcc -I src -o $@ $^

When you run this and sub/file.o doesn't exist, GNU Make
makes no effor to make it, nor does it complain that it doesn't exist!
It just passes the name to the linker via $^ and the linker complains.

IOW, if "file.o" is needed and doesn't exist, GNU Make complains.
But if "sub/file.o" is needed and doesn't exist, GNU Make just
assumes it's uptodate! Amazing.

If "file.o" is needed and missing, GNU Make complains. The fact that
if "sub/file.o" is needed and missing causes GNU Make to just assume
it is up-to-date is a remarkably unhelpful feature. I cannot
immediately imagine how this behavior is justified (but bet
it is!). UX fail. In any case, @MadScientist has the fix.


Your pattern rule does not match because, given sub/file.o,
it correctly matches %.o, but then also requires that a prerequisite
of sub/src/file.c exist, which was not what you intended and
will not match.



** semicolon

Semicolon lets you put action on same line as rule,
which I initially deemed not particularly useful. But
now I kind of like this:

a :SOME_OPERATOR: ; do
    --indented Lua statements!
end

Of course, you could just make a rule that if a lua
compound statement starts immediately after a dependency rule,
it can be in column 1 and will be treated as an action:

a :SOME_OPERATOR:
do
    -- indented Lua statements!
end

But I don't think so, because we want that to be code that is
executed in pass 2.

** distinguish special atoms from ordinary atoms.

User wants to have a target named ".AFTER" even though that's the name
of a special atom. Well, the user has to quote every instance of that.
So the atom name will be ".AFTER". The bound name will remove the quotes.

** Attributes
*** .AFTER
*** .BEFORE
*** .DEFAULT
*** .IGNORE
*** .PHONY
*** .PRECIOUS
*** .SILENT

** implicit directories
Maybe it's better to think of three different implicit directories, not just
two. The source directory is where we look for for our atom binding to files.
The output directory is where we expect to create targets. Finally, the
current working directory is where we expect to be when executing actions,
which causes pathnames in the action to be relative-adjusted. Or perhaps
even a fourth directory: the bludfile directory.

Should the bludfile directory matter? Probably not. The bludfile would
normally contain relative pathnames, and those would be relative to the
CWD of the user running the blud command. If nothing else, really want
to allow bludfile to exist elsewhere for testing.

OTOH, if the bludfile directory is ignored when determining the "base"
directory, then you can't look in the bludfile and determine where
things are going -- it will depend on what directory the blud invoker
was in at the time. Also, having the bludfile directory be the "base"
directory for binding its relative pathnames is fairly required to
make sense of sub-projects (which I haven't really worked out yet).

So, suppose the bludfile directory is the "base". A 'build' sets
the output directory.

** binding
We can't be like Alcatel nmake and have a binding remain in effect
for tne entire execution. The reason is we want to support multiple
builds, like:
    blud debug release
When building "debug" a target atom needs to be bound to a different
output directory than when (next) building "release".


** define
The define keyword helps us avoid cluttering up the atom namespace and
also lets us generalize a mechanism. Define creates a target that you
can "build" to execute its associated code. Define can take extra
arguments that alter the behavior of the associated code. Define can
also contain Lua and/or blud statements that may or may not get executed.

The syntax is:

define <type> name [args]
...  -- optional rules and macro assignments
end

In phase 1, this is translated into the Lua code:

if blud.DEFINE_TYPES[<type>] then
    (function (name, args)
    end)()
end

But "define type <name>" does NOT create a target, but rather a
name that can only be used as the typename for another define.


It all begins with a <type> of "type":

define type build
do

end
end


** command-line target references
Besides "-t <test_name>" and "-b <build_name>" maybe allow it like this:
    blud debug:util
so a:b means target "b" inside defined unit (test/build) "a".

** for-each actions
The normal rule looks like this:
    target : prereq1 ... prereqN
        action
and action is executed once for the target and has access to all the
prerequisite atom names. But in testing, we want to execute the same
action against a big list of tests.  The make way of handling this is
an implicit rule so that, e.g., test%.out depends on test%, and target
depends on test*.out. Which is... OK.

But that's not really identical to: perform this action for-each
of the following specific "prerequisites".


I guess the problem I'm getting at is I don't want the complexity of
defining an implicit rule if I can avoid it. But it's also the complexity
of naming "object" files instead of the source files.

define test
all :TEST: test*
    blud -f $<
end

In this example, the :TEST: operator knows it is inside a "test". It knows what
the associated build is and its OWD. And, uniquely, it will execute the action
once for each of the prerequisites.

Inside a "test", all the atoms are presumed relative to the test directory.
But actions are presumed relative to the OWD set by the associated build.
So in this example. blud will cd to the build directory (e.g., ./debug),
then execute "blud -f $<", where the $< will automatically expand
to "../test/testxxxx".

A "build" directive changes the OWD from its default of ".". But a "test"
directive changes both the source directory AND OWD from their defaults.
It gets the OWD from the associated build.


** virtual atoms
Atoms (targets/prerequisites) are assumed to be files, but they could
really be Lua functions. For example, the "output file" of a test
could be a Lua function that checks to see if that file meets certain
requirements. The default atom would be a Lua function that returns
the timestamp for the named file.



** quoted pathnames
We need quotes, since for example:

if : a.c b.c

would be mis-interpreted as a Lua IF statement. However,
we can't have the backslash be the escape character in quotes
because of Windows path conventions.


** Appending to macro
GNU Make says you can't do this:

CFLAGS = $(CFLAGS) -O

But I think I can handle that. CFLAGS is always a reference to an
anonymous function that returns a string. So this problem solves itself!
Almost. The initial definition of CFLAGS is a reference to an anonymous
function that expands its text. Any variable references in that
definition are indirect-by-name function calls to expand *that* variable.
When (re)defining CFLAGS, we are constructing another anonymous function,
the only difference is that when we encounter embedded self-reference,
we use a direct pointer to the anonymous function instead of indirect-by-name.
The anonymous function associated with CFLAGS will get clobbered by
a new one, and the previous anonymous function only exists via an embedded
reference.

Really not sure why GNU Make didn't do it this way. It essentially does
almost all the same work by allowing a += operator. I think there's no
need for the GNU Make "two flavors" of variables.

I guess the issue is "functions":

    Another disadvantage is that any functions referenced in the
    definition will be executed every time the variable is expanded. This
    makes make run slower; worse, it causes the wildcard and shell
    functions to give unpredictable results because you cannot easily
    control when they are called, or even how many times

CFILES = $(wildcard *.c)




** Phase 1
We are just copying input to output except there is a small transformation
for non-Lua lines. This is simplified because we don't let the user put
Lua code in column 1 unless it is the beginning of a compound statement:
    do/end
    (local) function/end
    if/else/elseif/end
    for/do/end
    while/do/end
    repeat/until
    local

The result of Phase 1 is a Lua program that, when executed, produces
blud.phase2_text. This is the set of blud (not Lua) statements that
must be parsed and executed to create the dependency graph.

** Phase 2
Now we execute the Lua program created by Phase 1 to create blud.phase2_text
and parse blud.phase2_text to create make variables and the
make dependency graph. Macros

In this parse, macros must be expanded.

** Parsing

A line is non-Lua if it starts in column 1 unless it
starts with one of:
    if    else   elseif then end do for repeat until while function local

A line is non-Lua if it starts in column 1 and:
    a) contains a '$' that is not '${'or
    b) starts with <identifier> <assign-op> or
    c) looks like a rule: one or more space-separated atoms followed by colon

A line is also non-lua if it is non-blank and indented following a rule

A line is also non-Lua if it is indented but starts with a $<whitespace>:
if ${OS} == "Windows" then
    $ OBJS += winrtl.obj
end

However, because of comments and string constants, these rules are not
sufficient.


A line is also non-lua if it is non-blank, indented, and follows
a rule.

*** Parsing: identifying blud statements
A blud statement must look like:
a) name <assign-op> text
b) <name-list> <colon-op> <name-list>
c) <name-list> <colon-op> <name-list>
   <indent><actions>

** GNU Make
*** macro fails
SET = A = you da man
$(SET)

a :
	echo $(A)
	echo $(SET)

This Makefile gives you the dreaded "missing separator" error on
line 2, even though the documentation says:

    Variable references can be used in any context: targets,
    prerequisites, recipes, most directives, and new variable values.

However, this quite similar construct works as expected:

SET = a : b
$(SET)

b : ; echo making b

a :
	echo $(SET)

And this works as well:
COLON = :
a $(COLON) b

b : ; echo making b

a :
	echo $(SET)

So what exactly are the rules for where variables can be used? Who knows?


** Secondary Expansion

Seems mostly about being able to modify rules with information not
available until all the rules have been parsed. Things probably better
done in Lua.

.POSTPARSE: a b
    function (target)
        print("Got called for each target. This one is: " .. target.NAME)
    end

Problems:
    a) just want a function call independent of any targets
    b) want function called with a list of targets

Waitaminute, "second expansion" is really kind of a subset of the :: operator.
Take all-too-tricksy example from page 18 of GNU make manual:

.SECONDEXPANSION
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib : $$($$(@_OBJS))
<><><><><>
main_OBJS := main.o try.o test.o
lib_OBJS  := lib.o api.o

main lib :AddObjs: _OBJS

function AddObjs(target, prerequisites, action)
    $ $@ : ${ $@ .. "_OBJS" }
end
<><><><><>



* log
** <2024-08-26 Mon>

Proposed meaning of "::" rule is: "Treat specially any dependents that exist and have no build rule."
So, given this case:

prog :: a.c b.c special_crt.o

When building "prog", it notices there is a "source dependency list"
in addition to the normal dependency list. For each entry on that list,
if it exists and has no rule to build it, then a search for transformation
rules begins, possibly resulting in a transformed name being added
to the dependency list. Otherwise, the name itself gets moved to the
dependency list.

** <2024-08-22 Thu>

Breakthrough. The implicit rules essentially represent code that is
executed when we don't know what to do with a target.  The decision
about whether to "execute" an implicit rule is hidden in the algorithm
for deciding if the rule matches the current target. And then "executing"
the rule is adding to the current dependency graph.

We can make the decision about "does this rule match" explicit
and under control of the rule itself by executing the code and
checking its return value (which will be nil if there is no return
statement). Let's suppose that any return value other than false
means that the rule took effect.

Here's a rule that just prints a debug statement without
affecting any implicit associations:

% : ; do
    print("searching for rule for '" .. $1 .. '"')
    return false   -- this rule doesn't match
end

Here's a rule that conditionally matches:

% : ; do
    if $1:match(".*secret.*") then
        $ $1 : secret
        $     echo "You found the secret!"
        return true
    else
        return false  -- this rule doesn't match
    end
end

<><><><><><>
Actions are a mix of shell/Lua/blud code. Here's a parsing problem:

a : b
    if os.clock() % 2 then
        $ c : d
    end
    if #$@ > 1 then
        $     echo "it's longer than 1"
    else
        $     echo "it's not longer than 1"
    end

If os.clock() returns an even number, then this is a blud syntax
error. It will see an indented action, even though there was no
previous unindented rule.

Best simplification is that embedded blud directives must be
consecutive. IOW, they must occur in the same blocks that
would be required if they weren't embedded. So, the legal
equivalent of the previous freaky example would be:

a : b
    local msg
    if #$@ > 1 then
        msg = "it's longer than 1"
    else
        msg = "it's notlonger than 1"
    end
    if os.clock() % 2 then
        $ c : d
        $    echo "${msg}"
    end



** <2024-08-21 Wed>

Think, think, think. I'm asked to update x.y. The user gave
no explicit action for updating x.y, so I cannot say for sure
it is an output file (and therefore cannot bind it yet). Here
is the context I have for trying to choose an implicit rule
for updating x.y:

- x.y, the partially formed target
- its prerequisite list
- the target that requires x.y to be updated
- and *its* prerequisite list
- all variables currently in scope
- the existance of files in the filesystem

GNU Make has: "old-fashioned" suffix rules and more flexible pattern rules.

"static pattern rules" are really a more flexible way to specify
explicit rules. Any target of a recipe-bearing static pattern rule is
given an action and will never be involved in an implicit rule search.

Given a tool that creates output files from input files, it pretty
much always has the same form.  Consider the C compiler. We might want
some files compiled with different options, but we don't make separate
implicit rules to match those files. Instead, we use variables to
alter the command-line of the tool.

So half the work of the implicit rule is deciding what tool to use,
and the other half is manipulating file names to create a new output
file.

What if we make the most primitive escape-to-lua implicit rule
syntax first?

%.o :CALL: %.c
    do
        local dot_o, dot_c = ...
        
    end
%.c :CALL: -- a source rule because it has no prerequisite?
    do
    end

OK, you have a source rule:
prog : *.c
and you're asked to update "foo.c". If there is an action already
for "foo.c", you do that. If "foo.c" now exists, you look for a
source implicit rule. If you find one, then you use that implicit
rule to generate dependencies. You replace the "foo.c" dependency
with the outputs of the implicit rule and update them instead. If
there was no source implicit rule

Really, if you're walking a list of patterns, you're just going
down a list of function calls, until one of them claims a match
for the target you want to update.

Do we need a separate source rule operator?

prog : a.c b.c

update prog means update a.c. No rule to update a.c. No implicit
rule to update a.c. There is a rule to produce a .o from an a.c,
but should we use it? Maybe "prog" is just a target that copies
its prerequisites to a backup folder.


** <2024-08-20 Tue>

Stuck on implicit rules.

<><><><><><><>

I'm trying to get to a point where this works via primitives,
not via a special, hard-coded operator:

prog :: a.c b.c c.o luajit/luajit.a

Notice that there is a mix of source and object files on the right.
blud cannot know, a priori, that c.o and luajit.a are NOT source files,
since the whole point of the rule could be to copy files elsewhere.

I was settling on this single rule being used for both
inferring output and source files:

%.o : %.c
    $(CC) -c $< -o $@

But look at this rule:

%  : %.o
    $(CC) $< -o $@

We see that a .o file could be an output file and could
also be a source file. If we see a.c on a :: rule, we
look to see if a.c can generate an output file. It can
because of the %.o:%.c implicit rule. But by the same
rule, we ask if c.o can generate an output file. It can
because of the %:%.o rule. So we end up believing that
prog depends on an executable linked from c.o!

Core Issues: given a prerequisite, we want to control whether
or not it should be replaced by an output file it can generate.

A :: operator could imply the answer is "yes" for all its
prerequisites. But that's the wrong answer for c.o here:

prog :: a.c b.c c.o luajit/luajit.a

We could say the implicit rule must also use a :: operator
for the source file to be considered. So, if there is no
rule like this:

%.o :: %.c

The c.o in the above example would do the right thing, then.
Is there a case where we want c.o to generate an executable
via a source rule? Here's an unrealistic case:

exes :: a.o b.o c.o
-- expands to:
exes : a b c
a : a.o
b : b.o
c : c.o

If I really wanted that to work, would write:

exes : a b c
% : %.o ; link command


<><><><><><>
If "c.o" is a prereq in a source rule, should we really be
looking for it anywhere but the source directory? I think
not.


<><><><><><><>
Here's another example:

blud :: blud.c oslinux.c bludlua.c
bludlua.c : blud.lua cstr
    $(OWD)/cstr $< >$@

We go to update "bludlua.c" and the first thing we do is BIND it.
Because bludlua.c has an action, it gets bound to $(OWD)/bludlua.c.
Then we transform it to bludlua.o. Hmmm, I think it all works.
<><><><><><><>


blud :: *.c
This doesn't work because one of my .c files is an output file
(generated by running cstr).


** <2024-08-19 Mon>
Thinking about whole pattern matching approach to locating
implicit rules. In classic make, we are given an output file
and have to guess the name of the source file that made it.
For source operator, we will be given name of source file
and the matching implicit rule will tell us how to create
name of output file.

In GNU make, the implicit rule can have more than one prerequisite.
Should we allow that? Not today.

So, must detect implicit rule during parsing, and index it two
ways: by target and by prerequisite. Well, really, the order of
the implicit rules is what matters.

GNU Make does not require implicit rules to appear before they
are needed, and I guess that makes sense.  So, 


** <2024-08-18 Sun>

Here's my current testing idea:

test : test/test[0-9][0-9][0-9][0-9]
    echo "Finished running tests"

test%.out : test%
    echo "test $@ $<"

I want to type things like "blud release test", so the 'release' build
sets the output directory to "./release" and the output of test runs
will be stored on a per-build basis.

But probably the default for testing should be this:
    - output directory defaults to build output directory
    - source directory defaults to named directory containing test info
    - current directory defaults to build output directory

This is so I can write a rule like this:

test%.out : test%
    ./blud -f $< -o $@

Although, is that really harder than:

test%.out : test%
    $(OWD)/blud -f $< -o $@

I guess point is we really wanted to avoid having to explicitly mention
special directories like $(OWD) in recipes. OK, can we make the syntax
default to the previous example? We will want to set the OWD, SWD, and CWD.

test  :TEST: ./test test[0-9][0-9][0-9][0-9]

Groping for :TEST: being a scope above build that implicitly (optionally explicit)
sets the $(SWD) and $(CWD). The user will have specified a build before
this test, so we can set $(CWD) to $(OWD) without knowing in advance
what $(OWD) is. Maybe we end up with:

test :TEST: test[0-9][0-9][0-9][0-9]
    ./blud -f $< -o $@

    
No! Always want almost all paths mentioned in bludfile to
be relative to bludfile dir, for clarity. So:

test :TEST: test[0-9][0-9][0-9][0-9]
    ^blud -f $< -o $@

Wildcard of *.c is a modest convenience. Not too high a burden to
have to mention all your source files in your bludfile explicitly.
But it's more important to tests. You don't want to have to modify
your bludfile every time you add or remove a test!

So I'm back to this:

test: test/test[0-9][0-9][0-9][0-9]
    echo "All tests complete"

test%.out : test/test%
    $(OWD)/blud -f $< -o $@

It's not the worst. But it doesn't really work. test0001 is a
source file but "test" should depend on $(OWD)/test0001.out.
Maybe we have to say:

test :: test/test[0-9][0-9][0-9][0-9]
    echo "All tests complete"

And the "::" says "assume the prerequisites are source files". The
resulting being the wild card expands into files like test/test0001,
and when "updating" test/test0001, we check for implicit rules
and find a match here:
    
test%.out : test/test%
    $(OWD)/blud -f $< -o $@

This is some serious tweaking to core algorithm. Updating
a prerequisite (may) gives it a corresponding "output" file,
and those output files become the prerequisites that $^
refers to!
<><><><><><><>

if "::" means "treat these prerequisites as source files,
what happens here:

prog :: prog.c crt.o

We go to update prog.c, find it exists in the source directory,
find there is a rule to create output file (prog.o), and associate
prog.c with prog.o so the latter becomes the prerequisite. But
then we go to update crt.o, find it exists, and regrettably find
that there is a rule (%.exe : %.o) that matches it, so its
corresponding prerequisite becomes crt.exe! Not what we want.

If our syntax says ALL these prereqs are sources, then we need
a syntax that lets us mark individual prereqs differently. How
about "::"? So, you say:

prog :: prog.c ::crt.o

On the rhs, a "::" prepended to a filename inverts the original
colon operator, so you could say:

prog : $(OBJS) ::prog.c

<><><><><><><>
Devolving :: into primitives is good, but I haven't said how this
actually works:

prog :: *.c

The matching .c files get associated with .o files that get built.
But how is it specified what command is used to link all those .o
files together?

First, we must handle the problem of identifying executables.
By the time we are ready to perform the action for prog,
all manner of rules may have been generated:

prog : a.o
prog : b.o  -- etc.

We don't know what "type" prog is, but we know it has .o files
among its prerequisites. GNU make rules can only handle this
in the special case of you are using a .o with the same prefix
as the executable:

prog : prog.o b.o ...

Works because there is a rule:

% : %.o

And the search for a rule match is such that this will match if the
target is anything, and any one of its prerequisites is the target
name followed by ".o".  So, we need a more powerful search for
implicit rules.

Another reason we need a more powerful search is GNU Make can
only "see" the .o files, so it doesn't know if it's compiling
C, or C++, or something else. It just assumes C. Here's an
annoying case:

prog : a.o b.o

If both a.o and b.o come from C files, we want the linker command
to use gcc. Otherwise, if even ONE of them is C++, we want the
linker command to use g++.



<><><><><><>
Could do build variations like this:

debug_$(OS)_$(COMPILER) :BUILD:
    $ CFLAGS += -g

Then you would run "blud -c OS=win COMPILER=clang debug"
Ooops -- that sure doesn't work. What is the "debug" target on the commandline
which doesn't appear in the bludfile? Ah, maybe it's like this:

debug :BUILD: ./debug_$(OS)_$(COMPILER)
    $ CFLAGS += -g


** <2024-08-14 Wed>
Might want to multiplex builds off of O/S and also by compiler.
For example, might want clang/gcc/vc/icc builds on both Windows and Linux.
Can just cram it all in directory name like: windows_clang_debug and
windows_clang_release.


** <2024-08-04 Sun>
I have a syntax for allowing blud statements in actions, but
can I have a syntax for defining actions that take place before
a build of the target?  Guess I already have that too:

do_stuff :BEFORE: some_target
    $ name = foo

right, but there assignments happen in global scope, not scope of
some_target. So I can control *when* assignments happen, but
not really the scope, other than the one-assignment-at-a-time
target scope syntax:

target : FOO += -g


** <2024-08-02 Fri>
wildcard characters in paths.  This is a second kind of "expansion" on
rule lines. Obviously must happen after macro expansions.


** <2024-08-01 Thu>
.BIND gets called by .BUILD, and it adjusts the binding
based on the current scope values of OWD and SWD.

COMPILE.C   = $(COMPILE.cc)
COMPILE.cpp = $(COMPILE.cc)
COMPILE.c   = $(CC) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
COMPILE.cc  = $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c

OUTPUT_OPTION = -o $@

%.o: %.c
    $(COMPILE.c) $(OUTPUT_OPTION) $<

<><><><><><><><>

Some commands really want to be run in current directory. How
can I easily specify that? Maybe it's an action special character: ^


** <2024-07-31 Wed>

binding.

blud.scope_build is a placeholder scope. Basically, it adds a level
of indirection so that all the target scopes that point to it don't
have to be updated to switch to a new build. Switching to
a new build involves clobbering the blud.scope_build table
with information from a particular build, but the parent reference
is left intact.


** <2024-07-30 Tue>
Tests.
a) want to name the test (probably the target name)
b) want to list its dependents
c) want to be able to change CWD, OWD, SWD


the atom :TEST: opens a scope that is just below the :BUILD: scope.

Ooops, I don't have a syntax for embedding a shell command inside
Lua code inside an action. The "$ " syntax lets me embed blud
directives inside Lua code inside an action. Well, but note
than an action can only be attached to a target. So... you *can*
specify an action as part of a target:

test :TEST:
    for test in $* do
        $ $(SWD test} : ${test}.out
        $     ../blud -f $@ >
    end

Uncleaned mess, but maybe you get the idea. 


** <2024-07-26 Fri>
A macro body is either a string (already expanded) or
a table (array of strings and tables representing macro calls).
expanding.

Hmmm, can I use scope mechanism to handle param macros (like $(1), etc.)?
Probably, just need a new scope that takes a macro_actual and uses
it to look up any macro names >= 0.


** <2024-07-25 Thu>

B luajit, snake case. I need a new class which will
be called "blud.Macro". Please only write stubs for
member functions unless it's obvious how they should
work. 
I need the following member functions:
blud.Macro:new(body) -- return new Macro object with .body field set
blud.Macro:assign(new_body) -- replace existing body with new body
blud.Macro:expand(scope, call, stack) -- just a stub
blud.Macro:expand_call(scope, call, stack)

** <2024-07-23 Tue>

FEE = $(FOO)
FOO = $(FEE)

When evaluating reference, must always check for recursion.

FEE = 666 $(FOO)
FOO = $(FEE)

This fails a recursion check when FOO is expanded. Only immediate
recursion is supported. Really, this is to obviate the need for
+=.

x   = $(CWD)
FOO = x
FOO = $($(FOO))

That will equal:
FOO = $(x)

<><><><><><><>
Problem is macro_tokens_from_text gets conflated by needing to
insert body of assignee if it encounters assignee's name.
And the conflation seeps into macro_extract_call, with
which it is mutually recursive.  Maybe best I can do is
pass in a closure.

The closure must get called by macro_extract_call().
Once it has the call invocation, it can test if the
call is a self-reference, and... oh oh:

FOO = $1 + $2
FOO = $(FOO a,b) 777

Can't just change this to:
FOO = $1 + $2 777
must actually do weird eval to get:
FOO = a + b 777

So, when you detect self-reference, you can't just insert
the macro body tokens. You must locate and substitute out
any formal parameters




** <2024-07-22 Mon>
Must we have the "two flavors" of variable ala GNU Make?
Alas, probably so, since := variables must not be expanded
upon reference.  So this gives variables three kinds of
expansion virtual function: delayed reference, simple string,
or function call. All being variations on "function call".

** <2024-07-21 Sun>


** <2024-07-19 Fri>



** <2024-07-18 Thu>

I'm pointlessly insisting on making FOO = $(FOO) -g
work, just because GNU Make doesn't support it.
What a pain. Making a pass after the macro tokenization
is turning into a pain. But passing the name into the
tokenization process is a pain too. And decent error
messages are triple pain.

OK: if FOO is the target of the assignment, then we must find
$(FOO) during tokenization to do anything different. What do we
do different? We take the arg stack of the call and apply it to
the body of FOO to produce an array of tokens that we insert
into the result.

Ugh: if you're going to pass macro name into tokenizer, then
you have to pass scope too, since it may need to look up name.

Vague feeling that I'm missing some great simplification here.
Let it go.

Anyway, notice that passing in the name of the potential self-reference
to the tokenizer reduces the cost of handling self-references to
almost nothing when they don't occur, which is the overwhelming
majority of the time. So that wins. Just as well pass
the macro itself, which will include its name and its token string.
The macro will be nil if it does not already exist: easy to test
for and skip the complications.

When we detect self-reference, we must eval that macro using
the call site arg stack (not guaranteed to be empty). Then
we pretend the resulting token string was seen instead of
the macro invocation. Is this a different flavor of eval
than needed elsewhere? Hmmmm.

Yes it is, because you have to traverse macro tokens,
only expanding one particular macro, and producing macro
tokens instead of a single string.


** <2024-07-14 Sun>
We end up with a pretty weird parsing process. Partly because we're mixing
languages. If there were no Lua and the macro language was extended to
handle control structures and expressions, then there might be a fairly clean
separate macro pass.




** <2024-07-11 Thu>

If the output directory is beneath the current directory, we get
command like "gcc -o ./build/foo.o", which is uglier than referring
to "build/foo.o". Could clean this up if OWD (or whatever it gets named)
is a function macro like $(OWD $>.o). Or, could make a filename
syntax for it like: "gcc -o @$>.o"

Problem with latter is: have a new special character but really only want it
to be special in limited circumstances.

How about: $(OWD $<)?  Slightly less cryptic, doesn't create any new
special characters.

Back to macro lookup. Each scope is a function that calls its parent function
when a search fails. You must pass the scope function to any function that
expands macros. Let's use closure for this so you don't have to also
pass along any extra arguments the scope function requires.
<><><><><>



** <2024-07-08 Mon>
Macro lookup.  It would seem more functional to pass the relevant target, if any,
to the macro lookup function. But that doesn't work if we want to use Lua
metatable chains to implement the lookup chain, since the index operator
can't take an extra argument.

Maybe the metatable approach is a bad fit here. The order of scopes is
fixed (although the target scopes are constructed at runtime). Only
the first two scopes (target and automatic) need to have a target
passed to them.

Lookups happen when evaluating actions and when assigning "immediate"
macros and when evaluating rule definitions


** <2024-07-05 Fri>




** <2024-07-04 Thu>

What happens if you nest builds:

debug :BUILD:
other :BUILD:
all :  other foo
foo :: *.c

And then "blud debug". Well, you could push/pop the "build" environment when
encountering nesting. We could also generalize environments



** <2024-07-03 Wed>

Current thinking is a "build" is a target that sets environment
variables and whatnot. That then affects any targets that follow.
But if you want to do two builds in the same run, they might interfere
with each other. Already have hierarchical scope, which is not quite
what we want, because that requires the top of the hierarchy to specify
what is to be built--the problem of separating *what* and *how*.

What if we introduce a new scope, which is the "build scope". This scope
exists until the parent of the build is built, or until a new build is "built".
Fairly important. Suppose the debug and release builds have a rich set of
differences. Can't build both in one line unless each accounts for environment
changes the other may have made.



** <2024-07-01 Mon>
Attribute values. Attributes are simple if they are boolean:

.PHONY : clean all test

This simply assigns a true .PHONY attribute to each of its "prerequisites".
What if we want to have a non-boolean attribute.


** <2024-06-27 Thu>
Alright, I know roughly where I'm going with the syntax.

** <2024-06-26 Wed>

Insight: we already have a block-structured syntax, which is a block
of indented lines in the action.
<><><><><><>

But if define really creates a target, maybe we should just extend the
target syntax instead of creating the new define syntax. We want:

a) Ability to say target-specific macros are actually global
b) Ability for target to be ignored/hidden if not explicitly built by user
c) Ability to execute code before building
d) Ability to group multiple target-specific macros together (not really fundamental)

crazy idea: could expand the notion of macro scope to execution sequence.
IOW, you look up a macro definition starting with the current target,
then up the current build stack, then the "temporal scope", then finally
the global scope.

release :BUILD:
    $ global CFLAGS += -O2

debug :BUILD:
    $ global CFLAGS += -g

And :BUILD: was created by:

BUILD  :OPERATOR:
    do
        local path = $1
        if path == nil then path = $< end
        blud.make_dir(path)
        $ $< : 
    end


** <2024-06-24 Mon>
Why is it so hard to find abstractions?  GNU make ties what to make
together with the macros that specify *how* to make it. The workaround
is command-line definitions, which let you specify the macros controlling
*how* independently of *what* targets you ask to build.

It also moves the *how* onto the command-line--but the point of a build
language is to have specifications that have *all* the information about
*how* to build.

Also, overloading the colon operator to do assignments makes things more
verbose.

You can do this in GNU make:

debug : CFLAGS += -g
debug : all

In this case "debug" is really a name for setting one or more macros.
But it cannot be applied via the command-line. If 'all' depends on 'foo.obj',
you can't ask for the debug version of 'foo.obj' to be built. Again, this
is the problem of separating what from how.

So what is the primitive that gets us there? Targets whose macro
assignments alter the top of the macro chain. Then, if you "build"
that target, you are altering *how* any remaining targets get built.
Now, you could achieve this with the addition of one keyword to Gnu make:
add "global" to the "override", "private", and "export" modifiers:

debug : global CFLAGS += -g

Then if you did "make debug all", you would be specifying a *how* in front
of a *what*.

So, what we're really adding *functionally* to GNU make is:
    1) implicit directories (output, action, source)
    2) global macro assignments

But that still leaves the problem of *syntax*, because it needs to be
dead easy to define a debug and release build (and preferably also to
run tests).

debug :{
CFLAGS += -g
}

We are essentially assigning a bunch of attributes to a target.
That is advantage of "define <type> <name>" syntax, lets us
succinctly have different types of targets we are defining.

define build debug
    CFLAGS += -g
end

equivalent to:

.GLOBAL_ASSIGN : debug
debug : OWD = ./debug
debug : CFLAGS += -g

Can we generalize the "type" mechanism?

define type build name path
    if name == nil then
        error("Missing build name")
    elseif path == nil then
        path = name
    end
    -- make sure directory exists
    -- make 'name' a target with GLOBAL_ASSIGN
    $ OWD = ${path}
end


** <2024-06-20 Thu>
4am thought of new approach for "build". Make "define" directive able to
define: macro or build or test. A "build" is a set of directives and a directory
(for output files).

A "test" is likewise a set of directives and a directory where test data
can be found. But a "test" is essentially orthogonal to a "build", since
it always is executed in the context of some "build".

If you list the names of tests and builds on the blud command line, it will
first build the builds, then run each of the tests against each of the builds:
    blud test debug release

The case we expect to be the default is a directory that contains one file
per test. Therefore, we don't want this to require for loops or anything
fancy. The syntax for the default case must be simple and intuitive.


Example:

define build debug
CFLAGS = -g
end
define build release end

define test -- defaults to ./test
# OWD is set by context of associated build
all :TEST: test*
end
<><><><><>
anyways.  So, a "build" sets the output directory. A "test" sets the working
directory to the output directory of the "build", and the output directory
to something, probably relative to the output directory of the "build".

Should we unify the build/test concepts? It's not just about setting default
directories, because we want a "test" to be applicable to any particular
build. That really just involves setting implicit directories, but we
would like to refer to them by their build name.

What if you want to run blud from a build output directory? Maybe
command-line option


<><><><><><><>
Using "define" for multiple things. Maybe don't use it for macros, only test/build.
Multiline macro:
FOO = [[
a list
of things
]]

Multiline definition of macro that transforms newlines into spaces:
FOO = /[[
test001
test002
test003
]]

Or, waitaminute, what if when expanding macro in a rule, we automatically
treat newlines as spaces?

** <2024-06-17 Mon>

** <2024-06-15 Sat>

Argh.  build/end is ambiguous:

if ...
build debug
end   <-- end of 'build' or end of 'if'?

Now, you could say "you should really indent that anyway" like so:

if ...
    $ build debug
    $ ...
    $ end
end

Well, this is not so bad if you say "blud code inside lua must be marked by $".
Philosophy: $ is already a special character in make, and not a special character
in Lua.

build debug
    $ CFLAGS = -g
end
<><><><><><>><>
OK, kind of want to stop and handle Lua comments, because my first
test file has them. Is it easy? Maybe just allow Lua-style comments
and quoted strings everywhere.

1) line that starts with <whitespace>*-- is single-line comment we can skip
2) line that contains


** <2024-06-14 Fri>
OK, macros do something. Should I implement "build" keyword next?
build <name>
...
end

is really same as:

if $(BUILD) == <name> then
    $ ...
end

except we throw some default behavior in there. We make sure
the <name> is a directory or can be created as a directory.
We set the output working directory (OWD).


** <2024-06-13 Thu>
Make macros do something. Why am I so slow?  Let a macro always
be a function that returns a string. If it was a ":=" style macro,
the string is constant. Otherwise, the string is generated from
an array of string constants and references to other macros
(functions). Don't worry about macros with arguments for now.

Simpler: always reparse late-binding macro. Then, a macro is
always a string, just have to keep track of whether it needs
expanding or not when you ask for its value.


** <2024-06-08 Sat>
Another day, another run at progress.  Phase 1 produced a Lua program.
Phase 2 produces blud.phase2_text, the actual bludfile directives
that will be read in this invocation of blud. Phase 3 takes each line,
performs any required variable substitution, then executes that line
(which either performs variable assignment, a dependency rule, or
associates action text). No multi-line variables allowed except in
actions, so can really do this line-by-line, no input stacking.
Every line in will be a line out.


** <2024-06-07 Fri>
to expand macros, must also a) execute macro definitions as they appear and
b) detect indented actions so we don't expand them. And c) detecting indented
actions requires detecting dependency lines. Can't cleanly separate macro
expansion from parsing!

State 0: expand all macros, char by char
    
    got 1st "name"

UGH! Implausible to ever generate good error messages! Back to restricting
use of macros.

Name <assignop> macros_OK
macros_OK <depend_op> macros_OK
    macros_OK

special:

build <name>
end
define <name>
end
define /<name>
end

Macro expansion pass:
1) if looks like macro assign op, do the operation, line won't appear in output
2) if looks like dependency line, expand all macros (multi-line not ok), copy to output
3) if indented, just copy to output

example:

define ACTION
cp $^ foo
echo foo!
end
OBJS = a.o b.o c.o
program : $(OBJS)
    $(ACTION)
<><><><><>
program : a.o b.o c.o
    $(ACTION)



** <2024-06-06 Thu>


** <2024-06-05 Wed>

OK, let's make phase 2? 3? expand macros. We assume that we can
rigorously identify non-lua lines even in the face of macros. Phase 1
was creating the Lua code that only has to be regenerated if the
bludfile changes.  Phase 2 executes that code to create
blud.phase2_text.

Should we expand macros while appending to blud.phase2_text, or in a
separate pass? Separate pass! Make things as clear as possible. Want
access to text output of phase 2 that shows what (including macros)
is the "real" input to the graph construction. Let's see problems:

FOO = FEE = a.c
$(FOO)

This is an example GNU Make fails on. We see $(FOO), we're not
in a macro definition, we're not in an action, so we expand it.
Ah, that's why GNU Make fails, I bet. Maybe. You have to not
only expand it, but then execute it (phase 4?).

So, the trick in a macro expansion pass is that there are two
contexts where macros should not be expanded: macro definitions
and actions. But those contexts cannot always be identified
in a single-pass macro expansion:

NAME   = Foo
VALUE  = Fee
MACDEF = $(NAME) = 
$(MACDEF) $(VALUE)
-- expands to
Foo = Fee

Well, maybe the only problem is knowing we're in an action:

X = foo!
RULE = a : b
define ACTION
    echo $(X)
end
$(RULE)
$(ACTION)
-- expands to
X = foo!
RULE = a : b
define ACTION
    echo $(X)
end
a : b
    echo $(X)


Really, really want to think in terms of variables instead of macros.
If you want to do weird stuff, do it in Lua!

What if: variables are only expanded in lhs/rhs of rule or in actions?
If you want them expanded anywhere else, you have to explicitly
say so.

Or maybe we just support simple macros and if you get into trouble
it's your own fault for not switching to Lua.

Do we recognize a macro definition in the expansion of a
macro? That is, the exact case where GNU make fails:

SET = A = you da man
$(SET)
a :
	echo $(A)
	echo $(SET)

OK, let's go back to variables, not macros. Variable/function
invocations can only happen inside variable definition,
inside variable invocation, or inside action. THEN can I have
a simple expansion pass?

And... also want to handle spaces inside filenames. Two main
uses for variables are actions (command flags) and filenames.
What if I DO have two flavors of variable, but they are:
array of filenames, and text.

OBJS      = { "file with space.txt" a.c b.c c.c }
EXTRA_OBJ = d.c
program   : $(OBJS) $(EXTRA_OBJ)


** <2024-06-04 Tue>

Why am I stuck? Little things. What are the exact rules for where
variable expansions can occur?  Desire to indent inside build/end.
Can I expand variables in phase 2? Big things. How to handle inference
rules. How to handle source prerequisites. How to detect executable.

Really want to expand variables in phase 2 because this potentially
helps make error messages better. Can easily print out "expanded"
lines for error messages, so user sees what the line became.

OK, so every non-lua line must look like rule or variable
assignment. Variables can only be expanded on rhs of variable
definition, or either side of dependency rule. Because: before
macro expansion... Hmmm, not sure.



Do I really have to introduce build/end? Certainly want to
avoid requiring conditional code to make different builds build
differently. build/end is basically away to group blud statements,
and must face the problem of wanting to indent statements that
are otherwise supposed to start in column 1. But we already
have indentation.  What about:

debug :BUILD:
    OWD = ./debug
    CFLAGS = -g
    program : debug.c
        $(LINK) <stuff>

Better:

debug : .BUILD

Still, a "build" directive is clearer, isn't it? And maybe it
should just allow indentation:

build debug=./debug
    CFLAGS = -g
    program : debug.c
        $(LINK) <stuff>
end

But "just allow indentation" collides with our simple rule for
identifying Lua: a Lua keyword starting in column 1.

OK, blud statements only require indentation to identify actions,
which must follow a non-indented rule. So, inside a "build" directive,
the indentation level is set by the very first line, which cannot be
(conceptually) indented:

build debug
    CFLAGS = -g
    if $(OS) == "Windows" then -- started in "virtual" column 1!
        program : windows.c
    end
end


** <2024-06-03 Mon>
CMake is a giant-ass preprocessor for make, essentially. But we should
be able to get more or less equivalent functionality just by extending
the general mechanisms of make, which is what blud can do.

Back to this:

program : a.c b.c

Really need to generate additional rules for this while building
the update graph. Initially, the graph is as written: program is
target and "a.c b.c" are the prerequisites. We *could* also consult
the filesystem at this point for more information. "program" may
or may not exist, but for sure we have no recipe for updating it.
Really, "program" is a dead end for determining how it should be
updated. So we step through its prerequisites.

"a.c" can tell us that it can produce "a.o", and "a.o" can tell us
that it is most likely used to make ".exe", and second most likely
used to make ".lib". So we guess that program is a ".exe", which
the user could make explicit with:

program :.TYPE: exe   -- I bet there's a better syntax!








** <2024-06-02 Sun>
Thinking of the dreaded implicit rule tangle. Was gonna say the "::" operator
is just hard-coded function that tries to generate the right rules from list
of source file prerequisites. But I think I've seen at least one make that
consistently had the user refer to source, not object, prerequisites.

program : a.c b.c

This has to eventually get translated to:

program : a.o b.o
    <linker command>

In a way, the "::" operator does what tools like CMAKE does, translating
a higher-level directive into detailed make rules.

This is relevant to the implicit rule problem, because the user writes:

program.exe : a.obj b.obj

which leaves the make utility to guess what the source files were for
a.obj and b.obj, even though the user knows perfectly well they were
.c files and would prefer to work with those names.

OTOH, there is the much less frequent case like this:

tool_name : a.c b.c   -- tool_name is a directory!
    cp $^ tool_name

Returning to this:

program : a.c b.c

It really should get translated to this:

program : a.o(a.c) b.o(b.c)
    <linker command>

where the parens indicate exactly what file the .o name was derived from.
GNU Make implicit rules for linking only really work if you happen to be
writing in C, since the object file dependencies lose the information
about what the source file extension was.

So, maybe the syntax should allow specifying which prerequisites are
source prerequisites, and what object files should be made from them.
So what would this mean:

program : <a.c <b.c

It means "a.c is a source file, look up what it should create". Hopefully,
the lookup finds a rule that says:

%.o : %.c
    $(CC) $(CFLAGS) -o $@ $<

<><><><><><><>
Meh, start over. User wants to write this:

program : a.c b.c

period. User types "blud program". blud updates "program", which first updates
"a.c". We don't know how to make a.c. In normal make, we see "a.c" exists and
has no recipe, so we just return its timestamp. But let's be different. Because
there is no recipe for "a.c", it's a "source". So let's look up our source
patterns and find that "a.c" matches "%.c", which is part of a rule that
says .c files produce .o files. So we "reflavor" a.c so it has two
components: source ("a.c") and output components ("a.o").

How/when do we know we have to build "a.o"? We kind of want to know that
"program" is of a TYPE that requires object files. But if "program"
does not exist, all we have to go on is its name, which (except under Windows)
will not typically contain a ".exe" or any other clue. Nor can we examine
the file, since it will often not exist.


<><><><><><>
Does "build" need to be a 1st-class concept in blud? Suppose we have
builds debug and release and we want to build debug/foo.o. Our bludfile
looks like:

{debug} : CFLAGS = -g
{debug} : program
program : foo.c

We cannot just say "blud foo.o" or even "blud debug/foo.o" because
neither of those targets implicitly reference the {debug} build.
First of all, for this to work, we really need to construct the entire
build graph, not just build it as needed. Let's translate the above
example into GNU make directives:

debug : CFLAGS = -g
debug : debug/program
debug/program : debug/foo.o
    <default link command>
debug/foo.o : foo.c
    <default CC command with OWD=debug>

Now, "debug/foo.o" is a known target. We could even, given "blud foo.o"
decide that ./foo.o is not a known target and look for $(OWD)/foo.o,
which would match "debug/foo.o". But we generally need to know what OWD
is set to to do anything, which is very close to just saying we need
to know which build the user is working with to do anything.

OK, so default build if no build directives is OWD=., works like
normal make. Else, if one or more build definitions and no specification
from environment or command-line, default build is the first one defined.

So, defining a build is essentially just assigning a name to the OWD.
The name is separate from the OWD to allow it to be short if the OWD
is long. In the most common case (debug/release) they would likely
be identical and the user need not distinguish the build name from
the OWD.

What syntax for defining a build? In the maximal case we need:
- build name
- OWD value
- zero or more build-level variable assignments
- zero or more build-specific rules
This suggests we need an enclosing construct with a begin/end line,
which is slightly ugly if we're requiring rules and variable assignments
to start in column 1. But let's go with that for the moment:

build debug=./debug
CFLAGS = -g
if $(OS) == "Windows" then
    $ program : debugger.c
end
end

This is slightly more verbose than I hoped, since a common construct
will start with:

build debug  -- creates ./debug if necessary, sets OWD and BUILD_OWD
CFLAGS = -g
end
build release
end
-- top-level variable BUILD is set to name of build

Note that you could do this:
function DebugBuild()
    if $(OS) == "Windows then
        $ program : debugger.c
    end
end
build debug=./debug
    $ CFLAGS = -g
    $ ${DebugBuild()}
end


** <2024-06-01 Sat>
I see the light! Can and should do away with macros. Let's say that this:

VAR = a $(B) c

translates to:

blud.set_var("VAR", function()
return "a " .. blud.get_var("B") .. " c"
end)

<><><><><>
OK, so we keep Phase 1, which does no macro expansion, just produces all the
non-lua lines of code. This allows Lua to control conditional appearance of
make rules and variable statements.

The resulting lines must be in one of the following two forms:
name <op> text

<text>* <colon_op> <text>*
(<indent><text>)*

Only <text> can contain variable expansions.




** <2024-05-31 Fri>
Phase 2. Can I expand macros on a per-line basis? Is macro expansion
different inside an action--do they all take place when the action
is executed? I think they must, else target-local variables would
not work.

So can Phase 2 just be macro expansion? Not quite, since it has to
know when it's in an action and not expand those macros.

Now is the time to fix macro problems!
What are macros for?
1) create values that can be referenced (list of filenames, command-line options, etc.)
2) create values that can be overridden on a target-scope basis
3) create values that can be overridden by command-line options
4) create multi-line values for actions that can be reused
5) create values with syntax friendly to space-separated lists
6) create delayed binding value references, so values can be built out of order
   IOW, this is value references


Now, you could always escape to Lua to make any variable you want:
do
    blud.macro_define("FOO", "Text of macro")
end

Ugh. See no wonderful improvements on macros and their "two flavors" ala GNU make.

Phase 2 must expand AND execute make code as it goes? Don't understand
expansion in actions.


a : b
$(ACTION)


** <2024-05-29 Wed>

1) parse blud file, create .luab
   non-Lua lines call function to append to text variable
2) run .luab, which creates variable with text of macros/rules
3) then expands text macros into another text variable
4) then parses text to create the graph
5) then uses the graph to update one or more targets

** <2024-05-28 Tue>

PROG = $(PROGNAME) : file1 $(OTHER)
PROGNAME = foo

if ${OS} == "Windows" then
    $ $(PROG)
end
fee : LATE = $(PROGNAME).exe
<><><><><><><><>
blud.append("PROG = $(PROGNAME) : file $(OTHER)\n")
blud.append("PROGNAME = foo\n")
blud.append("\n")
if blud.value("OS") == "Windows" then
    blud.append("$(PROG)")
end
blud.append("fee : LATE = $(PROGNAME).exe")
<><><><><><>
OK, have to write macro parser.



** <2024-05-27 Mon>
I started by parsing the blud file and converting it to Lua. But this cannot be
done in general at "compile" time, because of macros. Macros can introduce a runtime
requirement to do any sort of parsing I was trying to do at compile time. Worse, they
require character-by-character parsing because of:

objs = foo.$(OBJ)  -- can't tokenize until after macro expansion!

Actually, can avoid char-by-char processing if I first do a pass that expands
all the macros. Try some examples:

$(STUFF)
<><><><><><>
do
    local str = expand([=[
$(STUFF)
]=]
    parse(str)
end
<><><><><>
But that doesn't work either. Consider:
STUFF = a : b
$(STUFF)
    echo "Doing action"
Parser can't operate on each line independently, so when it hits echo line,
it needs to know previous line was a rule.
Also consider:
a : b
if ${OS} == "Windows" then
    $     echo "Doing Windows-only action"
end

It should help simplify if $ always identifies non-Lua code.
${} can still be used inside Lua code for convenient access to macros.

<><><><><><><>
We convert the blud text into Lua. We execute the Lua, which produces
the text of blud directives. We then parse the directives to create
macros and a dependency graph.  Finally, we use the graph to update
one or more targets.

STUFF = a : b
$(STUFF)
    echo "Doing action"
<><><><><><><>
do -- STUFF = a : b
    blud.macro_assign("STUFF", "a : b")
end
do -- $(STUFF)
    blud.append_text(blud.macro_expand("STUFF"))
    blud.append_text("\n")
end
do -- echo "Doing action"
    blud.append_text("    echo \"Doing action\"\n")
end

** <2024-05-25 Sat>

can blud rules be indented? e.g.:

if $(OS) == "Windows" then
    program : 
end


** <2024-05-14 Tue>



** <2024-05-13 Mon>

More than one lhs atom is just a syntax trick, so:
.ATOM : a b c d
means we're injecting code into these atoms. While:
a : b c d .ATOM
means .ATOM will get passed the rule before it is added to the graph



OK, really can't nail down graph when generating .lua code, because
variables can change at runtime via command-line options. So, what
is translation of:

a $(b) : c $(d)

do
    targets, prerequisites = blud.parse_rule([=[a $(b) : c $(d)]=])
end
-----------------------------------------------------

No, but wait. At least consider nailing down graph at compile time.
Because, you could always fall back to Lua code at run time that
does anything.

OK, can't completely nail down graph at compile time because of
wildcards, like "*.c". Don't want to give up that feature.

-----------------------------------------------------



.AFTER : a b c d e

a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when those atoms actions are to fire
c) it pretends the actions were successful
d) it asks to be called back when the parent finishes its action
e) when it is called back, it fires its own action finally

.BEFORE : a b c d e
a) it marks that attribute TRUE in its dependency list.
b) it asks to be called back when 




** <2024-05-12 Sun>

How about: primary way to inject Lua code into the process is via
special atoms. A special atom can appear on the left or right side of
a rule (though it may only make sense on one side or the other). The
name of the atom essentially identifies a Lua object that overrides 1
or more default behaviors of special atoms.  Function members of the
object will get called at various points in the processing. The object
will have access to a variety of information, including everything
about the rule.


** <2024-04-27 Sat>

When can custom Lua code be run? 

program: program.c
    cc -o program program.c

Now want to put products in a different directory.

all: program
