--[[
    sourcemap.lua: allow creating text that includes source map

    map is an array of entries:
        {filename, source_ln, dest_ln}
    A new entry appears in the source map every time the source filename
    changes, or every time a source line generates more than one output line
]]
    
local M              = {}
local buffer         = require("string.buffer") -- where we store
local map            = {}
local next_output_ln = 1


local function count_nl(text)  -- return count of newlines in a string
    return select(2, str:gsub("\n", "\n"))
end

M.output_buffer = buffer.new()
M.synced        = true

-- append lines generated by one line of source code
M.append  = function(filename, linenumber, text)
    -- see if we can skip adding a new map entry
    local need_entry = false
    local count      = count_nl(text)
    local previous   = map[#map]
    if count > 1 or (previous and (previous.filename ~= filename)) then
        need_entry = true
    end
    if need_entry then
        for i = 1, count do
            local entry = {filename=filename, source_ln=linenumber, next_output_ln}
            next_output_ln = next_output_ln + 1
        end
    end
    M.output_buffer:put(text)
end

M.append_file = function(filename, text)
    local entry = {filename=filename, source_ln=1, dest_ln=next_output_ln}
    table.insert(map, entry);
    next_output_ln = next_output_ln + count(text)
    M.output_buffer:put(text)
end

M.to_source = function(ln)   -- map an output line number to input file/ln
    for i = #map, 1, -1 do
        local entry = map[i]
        local ln_offset = ln - entry.dest_ln
        if ln_offset >= 0 then
            return entry.filename, entry.source_ln + ln_offset
        end
    end
end


return M


    
