--[[
    sourcemap.lua: allow creating text that includes source map

    map is an array of entries:
        {filename, source_ln, dest_ln}
    A new entry appears in the source map every time the source filename
    changes, or every time a source line generates more than one output line
]]
    
local M              = {}
local util           = require("util")
local buffer         = require("string.buffer") -- where we store

-- main reason to be constructible object is for unit testing
local Sourcemap = {}
Sourcemap.__index = Sourcemap

M.new = function ()
    return setmetatable({
        output_buffer = buffer.new(),
        map           = {},
        next_output_ln= 1,    -- number of next output line
    }, Sourcemap)
end


-- append lines generated by one line of source code
function Sourcemap:append(filename, linenumber, text)
    -- see if we can skip adding a new map entry
    local need_entry = false
    local line_count = util.count_char(text, '\n')
    local previous   = self.map[#self.map]
    -- if more than one output line for this input, or if it's a new file
    if line_count > 1 or (previous and (previous.filename ~= filename)) then
        need_entry = true
    end
    if need_entry then
        for i = 1, line_count do
            local entry = {filename=filename, source_ln=linenumber, dest_ln=next_output_ln}
            table.insert(self.map, entry)
            next_output_ln = next_output_ln + 1
        end
    end
    self.output_buffer:put(text)
end

function Sourcemap:append_line(filename, linenumber, text)
    return self:append(filename, linenumber, text .. '\n')
end

function Sourcemap:tostring()
    return self.output_buffer:tostring()
end

function Sourcemap:to_lua()
    local output_buffer = buffer.new();
    self.output_buffer:put("blud.sourcemap = {\n")
    for i = 1, #self.map do
        local entry = self.map[i]
        output_buffer:put(string.format(
                              "    {filename=%q, source_ln=%d, dest_ln=%d},\n",
                              entry.filename, entry.source_ln, entry.dest_ln))
    end
    self.output_buffer:put("    }\n")
    return self.output_buffer:tostring()
end

function Sourcemap:append_file(filename, text)
    local entry = {filename=filename, source_ln=1, dest_ln=next_output_ln}
    table.insert(self.map, entry);
    next_output_ln = next_output_ln + count(text)
    self.output_buffer:put(text)
end

function Sourcemap:to_source(ln)   -- map an output line number to input file/ln
    for i = #self.map, 1, -1 do
        local entry = self.map[i]
        local ln_offset = ln - entry.dest_ln
        if ln_offset >= 0 then
            return entry.filename, entry.source_ln + ln_offset
        end
    end
end

---[[UNIT_TESTS
do
    print("UNITTEST: sourcemap.lua")
    function test1()
        local sm = M.new()   -- create a new sourcemap
        assert(sm)
        local source_linenumber = 1
        sm:append_line("filename", source_linenumber, "output line 1")
        local lua = sm:to_lua()
        local expect = [[
output line 1
blud.sourcemap = {
    }
]]

        if expect ~= lua then
            error("test1 failed")
        end
    end
    test1()
    print("UNITTEST: sourcemap.lua complete")
end
--]]
return M


    
