--[[
    sourcemap.lua: allow creating text that includes source map

    map is an array of entries:
        {filename, source_ln, dest_ln}
    A new entry appears in the source map every time the source filename
    changes, or every time a source line generates more than one output line
]]
    
local M              = {}
local buffer         = require("string.buffer") -- where we store
local map            = {}
local next_output_ln = 1    -- number of next output line


local function count_nl(text)  -- return count of newlines in a string
    return select(2, text:gsub("\n", "\n"))
end

M.output_buffer = buffer.new()

-- append lines generated by one line of source code
M.append  = function(filename, linenumber, text)
    -- see if we can skip adding a new map entry
    local need_entry = false
    local line_count      = count_nl(text)
    local previous   = map[#map]
    -- if more than one output line for this input, or if it's a new file
    if line_count > 1 or (previous and (previous.filename ~= filename)) then
        need_entry = true
    end
    if need_entry then
        for i = 1, line_count do
            local entry = {filename=filename, source_ln=linenumber, dest_ln=next_output_ln}
            table.insert(map, entry)
            next_output_ln = next_output_ln + 1
        end
    end
    M.output_buffer:put(text)
end

M.append_line = function(filename, linenumber, text)
    return M.append(filename, linenumber, text .. '\n')
end


M.tostring = function()
    return M.output_buffer:tostring()
end

M.to_lua = function()
    local output_buffer = buffer.new();
    output_buffer:put("blud.sourcemap = {\n")
    for i = 1, #map do
        local entry = map[i]
        output_buffer:put(string.format(
                              "    {filename=%q, source_ln=%d, dest_ln=%d},\n",
                              entry.filename, entry.source_ln, entry.dest_ln))
    end
    output_buffer:put("    }\n")
    return output_buffer:tostring()
end

M.append_file = function(filename, text)
    local entry = {filename=filename, source_ln=1, dest_ln=next_output_ln}
    table.insert(map, entry);
    next_output_ln = next_output_ln + count(text)
    M.output_buffer:put(text)
end

M.to_source = function(ln)   -- map an output line number to input file/ln
    for i = #map, 1, -1 do
        local entry = map[i]
        local ln_offset = ln - entry.dest_ln
        if ln_offset >= 0 then
            return entry.filename, entry.source_ln + ln_offset
        end
    end
end


return M


    
